name: Stock News Bot

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설정 및 캐시 적용
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # 핵심: 이전에 설치한 라이브러리를 캐싱하여 시간 단축

      - name: 라이브러리 설치
        run: |
          pip install -r requirements.txt

      - name: 뉴스봇 실행
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
